-- A Personality Trait is affiliated with exactly one Stat, and under ENCLAVE:
-- Aspirant V1 that affiliation has mechanical weight: each Trait grants +1 Cap
-- to its Stat (ENCLAVE: Aspirant, pg. 3, restated pg. 6). A Cap therefore
-- cannot be computed from a character's row alone, and until now the
-- affiliation was nowhere in the database -- the wizard resolves it in the
-- browser (public/js/character-wizard.js, personalityMap / traitStats) and
-- drops it at the payload boundary, which carries only trait0/trait1/trait2.
--
-- Stored rather than derived on read. The vocabulary is closed today and every
-- one of its 48 words maps to exactly one Stat, so this column is derivable
-- right now; it is stored because pg. 3 makes Aspirant Traits "fully
-- customizable", and a self-made word has no vocabulary entry. Deriving would
-- return no Stat for a legal Trait and silently cost it a Cap. The vocabulary
-- decides the affiliation at write time; this column is authoritative at read
-- time.
--
-- Nullable here on purpose. public.save_character_atomic does not carry this
-- column until 20260919000002, so a NOT NULL now would fail every character
-- save. 20260919000003 adds it once every write path supplies a value.
ALTER TABLE public.traits ADD COLUMN stat TEXT;

-- One-time snapshot of util/enclave-consts.js personalityMap, generated by the
-- command in this task's Step 1 rather than retyped. A migration runs once, so
-- this is a historical record and not a second live definition of the
-- vocabulary -- the same reasoning as
-- 20260904000001_backfill_gear_category.sql, which froze the gear column split
-- the same way.
WITH vocabulary (word, stat) AS (
  VALUES
    -- The 48 rows printed by this task's Step 1 command, pasted verbatim.
    -- Do not retype them and do not abbreviate the list: the DO block below
    -- fails the migration if even one live trait name goes unmapped.
    ('indulgent','vitality'),
    ('fun-loving','vitality'),
    ('greedy','vitality'),
    ('optimistic','vitality'),
    ('forceful','might'),
    ('aggressive','might'),
    ('retaliatory','might'),
    ('brave','might'),
    ('tough','resilience'),
    ('blunt','resilience'),
    ('no-nonsense','resilience'),
    ('grim','resilience'),
    ('compassionate','spirit'),
    ('warm','spirit'),
    ('sentimental','spirit'),
    ('giving','spirit'),
    ('ambitious','arcane'),
    ('powerhungry','arcane'),
    ('haughty','arcane'),
    ('scheming','arcane'),
    ('self-controlled','will'),
    ('serious','will'),
    ('calm','will'),
    ('principled','will'),
    ('alert','sensory'),
    ('aloof','sensory'),
    ('organized','sensory'),
    ('wary','sensory'),
    ('smooth','reflex'),
    ('ingratiating','reflex'),
    ('easygoing','reflex'),
    ('sly','reflex'),
    ('enthusiastic','vigor'),
    ('gung-ho','vigor'),
    ('extroverted','vigor'),
    ('boisterous','vigor'),
    ('confident','skill'),
    ('cocky','skill'),
    ('showoffish','skill'),
    ('cool','skill'),
    ('opinionated','intelligence'),
    ('articulate','intelligence'),
    ('pretentious','intelligence'),
    ('analytical','intelligence'),
    ('carefree','luck'),
    ('cheeky','luck'),
    ('whimsical','luck'),
    ('complacent','luck')
)
UPDATE public.traits t
SET stat = v.stat
FROM vocabulary v
WHERE lower(btrim(t.name)) = v.word
  AND t.stat IS NULL;

-- Every one of the 981 live rows is expected to match. Fail loudly rather than
-- leaving a partial backfill for a later constraint to trip over.
DO $$
DECLARE unmapped integer;
BEGIN
  SELECT count(*) INTO unmapped FROM public.traits WHERE stat IS NULL;
  IF unmapped > 0 THEN
    RAISE EXCEPTION 'traits.stat backfill left % row(s) unmapped', unmapped;
  END IF;
END $$;

-- Twelve stats, the same list as util/enclave-consts.js statList and as the
-- twelve columns on public.characters. `stat IS NULL OR ...` is what makes the
-- constraint safe while the column is still nullable; 20260919000003 removes
-- the null half along with the nullability.
ALTER TABLE public.traits ADD CONSTRAINT traits_stat_known CHECK (
  stat IS NULL OR stat IN (
    'vitality','might','resilience','spirit','arcane','will',
    'sensory','reflex','vigor','skill','intelligence','luck'
  )
);
