// ar-7v3k check 8 -- the page editor's title -> slug auto-fill, which replaced a
// deleted 43-line inline script that tracked the same "was this auto-generated"
// flag in a data-autoGenerated attribute.
//
// WHY THIS MATTERS MORE THAN THE OTHER ALPINE CONVERSIONS. On an EXISTING page
// the slug IS the public URL (routes/pages.js:150 serves /pages/:slug). An
// auto-fill that re-fires on load, or on an edit to some unrelated field,
// silently rewrites that URL on the next save and breaks every inbound link --
// with no error, client or server. So the two behaviours under test are a
// non-change ("the slug must not move") and a re-arm ("but it must start
// following again when the slug is cleared"), and a non-change is the single
// easiest thing in a browser suite to assert vacuously.
//
// THE THREE VACUITY TRAPS THIS FILE IS BUILT AROUND -- read before editing:
//
//   1. `await expect(slug).toHaveValue(ORIGINAL)` after typing in the title is
//      ALREADY TRUE THE INSTANT THE PAGE LOADS. toHaveValue retries, so it
//      succeeds on its first poll and can return before the @input handler has
//      even run. It passes on a page where Alpine is dead, where x-model is
//      missing, where @input was deleted, or where the slug is about to be
//      overwritten one tick later. Closed three ways, all of them present in
//      the "does not move its slug" test below: (a) Alpine liveness and the
//      exact `auto` value are asserted BEFORE and AFTER the edit; (b) the edit
//      is settled on a POSITIVE signal (Alpine's own `title` reaching the new
//      string) before the non-change is read, and then re-read after a bounded
//      delay so a late overwrite still fails; (c) that same test ends with a
//      POSITIVE CONTROL on the same component -- clear the slug, type one more
//      character, and the slug DOES move -- so "it did not move" is a choice
//      the component made, not the only outcome the test could produce.
//
//   2. "Saving without touching the slug leaves the URL unchanged" PASSES IF
//      THE SAVE NEVER HAPPENED. A validation failure, a 403, a submit button
//      that is not really a submit -- all of them leave the slug exactly as
//      seeded. Closed by making the save carry a change that IS asserted to
//      land (the title), by requiring the post-submit navigation to reach
//      /pages/manage with no error banner (sendError HX-Retargets to #alerts
//      and never changes the URL -- util/http-error.js:44), and by re-reading
//      the row from the database.
//
//      CLOSING TRAP 2 IMMEDIATELY FOUND THE BUG IT WAS GUARDING AGAINST. The
//      save DOES silently fail: POST /pages/:id answers 404 "Failed to update
//      page" and the row is never touched. See the block below. The draft spec
//      this file replaces would have passed -- green, and reporting that the
//      slug is stable, on an app where saving a page is impossible.
//
// ** PRE-EXISTING PRODUCT DEFECT: THE PAGES CMS ONLY WORKS FOR PUBLISHED,
//    PUBLIC PAGES -- READ AND WRITE ALIKE **
//
// models/pages.js:1 binds EVERY query -- reads included -- to the ANON Supabase
// client (`const { supabase } = require('./_base')`), and no function accepts a
// client argument. `pages` has RLS enabled (migrations/20240101000000_baseline_schema.sql:1495-1538);
// the anon key carries no user JWT, so `is_admin()` is false and
// `auth.role() = 'authenticated'` never holds.
//
// READS (the wider half). getPages():43 and getPage():84 see only rows matching
// "Public pages are viewable by everyone" -- is_published = true AND
// access_level = 'public'. Measured as a signed-in admin:
//     fixture              /pages/manage   GET /pages/:id/edit   GET /pages/:slug
//     published + public   listed          200                   200
//     unpublished draft    NOT listed      404                   404
//     access_level=admin   NOT listed      404                   404
// So `is_published = false` and `access_level = 'admin'` are WHOLLY
// NON-FUNCTIONAL features: an admin cannot list, open, edit or even view such a
// page. canViewPage():185 -- which exists precisely to let admins through -- is
// dead code for them, because the row never loads for it to judge.
//
// WRITES. Same client, same reason:
//   - UPDATE matches 0 rows -> .select().single() returns PGRST116 ->
//     classifyError maps it to 404 -> POST /pages/:id answers 404 and a visible
//     "Failed to update page" lands in #alerts. Fails LOUDLY.
//   - INSERT is rejected outright with 42501 -> POST /pages answers 403 "No
//     access" and creates nothing (measured with an admin-token form POST).
//     Fails LOUDLY.
//   - DELETE matches 0 rows and reports NO error, so routes/pages.js:146 answers
//     204 with the row still in the database. Fails SILENTLY -- and note what
//     that does NOT mean: htmx 2.0.8 does not swap on a 204, so the manage-page
//     row is not removed and nothing on screen claims success. Measured:
//     {DELETE 204, row still visible, 0 error notifications, #alerts "", DB row
//     survives, still present after reload}. The button is inert. The real
//     defect is the 204 itself -- any non-htmx consumer (agent API, script,
//     future SPA) correctly reads it as "deleted".
//
// The RLS policies are NOT the problem: the same UPDATE and DELETE through
// createUserClient(adminAccessToken) succeed (1 row each, measured), and the
// Task 14 reviewer threaded `res.locals.supabase` through models/pages.js and
// its call sites temporarily and got UPDATE -> 302 with the row really changing,
// INSERT -> 1 row, DELETE -> row really gone. routes/pages.js already holds that
// client in `res.locals.supabase` (util/auth.js:57) and never passes it down.
// DO NOT "fix" this by swapping in supabaseAdmin: that is the service-role key,
// it bypasses RLS entirely, and it contradicts this branch's own fcb331e
// ("supabaseAdmin now only in _base + repositories").
//
// PRE-EXISTING, NOT A REFACTOR REGRESSION: bf10fc9 "Pages (#99)" (2026-02-05)
// adds CREATE TABLE pages, ENABLE ROW LEVEL SECURITY, all four write policies
// AND models/pages.js with `const { supabase } = require('./_base')` on line 1,
// in the SAME commit -- there is no window in which this ever worked. The
// deleted inline script was purely client-side slug bookkeeping and the form was
// already `method="post" action="/pages/{{page.id}}"` before the refactor.
//
// NOT COVERED BY A TEST HERE, deliberately: the read half is a Pages-CMS defect,
// not a slug defect, and check 8 is about slug stability. It is recorded in the
// task report and the ledger instead of adding a second permanently-red test to
// a suite that already carries seven. It is why every fixture in this file is
// seeded published + public -- anything else 404s on the edit form and this spec
// could not run at all.
//
// Consequently the round-trip test below is DELIBERATELY RED, in the same way
// as 03b-class-reassignment.spec.js and the reds in 10/11. It is split from the
// client-side half ("the form posts the unchanged slug"), which is what ar-7v3k
// check 8 is actually about and which passes today -- so a fix to the model
// layer turns exactly one test green and nothing else moves.
//
//   3. `fill()` IS NOT TYPING. It sets .value and dispatches ONE input event.
//      That is enough for x-model and @input, but the behaviour under test is
//      keystroke-driven and the interesting bug is a per-keystroke one: drop
//      `this.auto = true` from onTitle() and the refill still happens, so a
//      single-event test stays green while the slug stops following after the
//      FIRST character (the next keystroke sees `auto` false and `slug` no
//      longer empty). See the comment at public/js/alpine-components.js:42-51,
//      which calls out exactly this. The re-arm test therefore types with
//      pressSequentially and asserts BOTH the intermediate state after keystroke
//      one and the final slug after fourteen.
//
// Inherited from Task 10/11/13 and load-bearing here:
//   - public/js/app.js:970-989 replaces the whole <body> via an outerHTML htmx
//     swap on EVERY authed page load, discarding the Alpine component built by
//     the first parse. Both routes here are isAuthenticated + requireAdmin, so
//     that swap always happens; openForm() waits for networkidle so every
//     reading below is pinned to the post-swap component. Confirmed product
//     defect, worked around rather than fixed.
//   - `'auto' in Alpine.$data(el)` is the liveness test. NEVER `!!Alpine.$data(el)`:
//     $data falls back to mergeProxies([]) and hands back a truthy Proxy for any
//     element at all (Task 10).
//   - Absent != present-but-wrong: every reading in readSlugState is gated on
//     its element existing, and presence is asserted separately.
const { test, expect } = require('@playwright/test');
const { connect, newPrefix, profileForEmail, cleanupByPrefix } = require('../fixtures/db');
const { ADMIN_EMAIL, ADMIN_STATE } = require('../global-setup');

test.use({ storageState: ADMIN_STATE });

const prefix = newPrefix('page');

// THREE fixture rows, one per mutating concern, and deliberately so.
// playwright.config.js sets fullyParallel: true, so the tests in this file run
// concurrently in separate workers. The two submit tests get a row each even
// though neither can change anything today: the moment the model-layer defect
// above is fixed they both start writing, and a shared row would make them race
// each other's "the editor loads with the seeded title" preconditions and flake
// for reasons that have nothing to do with the code under test. A landmine
// defused ahead of whoever fixes it. The four read-only tests share the third.
const READ_TITLE = `${prefix}-read-title`;
const READ_SLUG = `${prefix}-read-handwritten-slug`;
const POST_TITLE = `${prefix}-post-title`;
const POST_SLUG = `${prefix}-post-handwritten-slug`;
const POSTED_TITLE = `${prefix}-post-title-edited`;
const SAVE_TITLE = `${prefix}-save-title`;
const SAVE_SLUG = `${prefix}-save-handwritten-slug`;
const SAVED_TITLE = `${prefix}-save-title-edited`;

// Both slugs are deliberately DIFFERENT from slugify(their title), because
// `auto: !initialSlug || initialSlug === slugify(initialTitle)` is what decides
// whether an existing page's slug keeps following. A fixture whose slug happened
// to equal slugify(title) would load with auto === true and the "does not move"
// test would be asserting the OPPOSITE behaviour to the one it names -- and
// would fail, looking exactly like a product defect. Asserted (auto: false) on
// load rather than assumed.

let db;
let readPage;
let postPage;
let savePage;

const seedPage = async (title, slug, createdBy) => {
  const { rows } = await db.query(
    `insert into pages (title, slug, content, access_level, is_published, created_by)
     values ($1, $2, $3, 'public', true, $4)
     returning *`,
    [title, slug, '# Fixture content\n\nBody text for the page editor.', createdBy]
  );
  return rows[0];
};

test.beforeAll(async () => {
  db = await connect();
  const profile = await profileForEmail(db, ADMIN_EMAIL);
  // Content is non-empty on purpose: #content is `required` AND the ToastUI
  // editor hides it with display:none !important (public/js/app.js:610). An
  // empty required control that is not focusable makes Chrome refuse to submit
  // the form at all, which would take the save test down with a browser-level
  // failure that looks nothing like the thing being tested.
  readPage = await seedPage(READ_TITLE, READ_SLUG, profile.id);
  postPage = await seedPage(POST_TITLE, POST_SLUG, profile.id);
  savePage = await seedPage(SAVE_TITLE, SAVE_SLUG, profile.id);
});

test.afterAll(async () => {
  // cleanupByPrefix's final statement is `delete from pages where title like
  // $1` (e2e/fixtures/db.js:79). This spec is the first to exercise that path.
  // Every title this file ever writes -- including SAVED_TITLE, which the save
  // test puts in the database -- starts with the prefix, so nothing the
  // developer owns is in range.
  await cleanupByPrefix(db, prefix);
  await db.end();
});

const editUrl = (id) => `/pages/${id}/edit`;

// See the app.js:970-989 note in the header: without this, readings race a
// <body> swap that is about to throw the component away.
const openForm = async (page, url) => {
  await page.goto(url);
  await page.waitForLoadState('networkidle');
};

// ONE non-retrying read of everything an assertion here could depend on, so a
// failure names WHICH cause fired rather than just "expected e2e-...-slug".
// Non-retrying is the point: a retrying assertion cannot distinguish "the slug
// never moved" from "the slug moved and this poll ran before it did" (Task 10's
// suite-wide lesson).
const readSlugState = (page) => page.evaluate(() => {
  const form = document.querySelector('#page-form');
  const titleInput = document.querySelector('#title');
  const slugInput = document.querySelector('#slug');
  let data = null;
  try {
    // NOT `!!Alpine.$data(form)`: $data falls back to mergeProxies([]) and is
    // truthy for ANY element, even one with no x-data ancestor. Presence of the
    // key this component declares is the real test.
    data = form && window.Alpine ? window.Alpine.$data(form) : null;
  } catch (_) { /* Alpine absent -> alpineInitialised stays false */ }
  const alpineInitialised = !!data && 'auto' in data;
  return {
    formPresent: !!form,
    titlePresent: !!titleInput,
    slugPresent: !!slugInput,
    alpineInitialised,
    // `auto` is the whole behaviour. It is never inferable from the DOM: a page
    // whose slug simply has not been touched yet looks identical either way.
    auto: alpineInitialised ? data.auto : null,
    alpineTitle: alpineInitialised ? data.title : null,
    alpineSlug: alpineInitialised ? data.slug : null,
    // ...and the DOM values alongside, because x-model has to write BOTH
    // directions. Alpine state alone would pass with x-model deleted from #slug.
    titleValue: titleInput ? titleInput.value : null,
    slugValue: slugInput ? slugInput.value : null
  };
});

// The positive settle signal. Until Alpine's own `title` holds the typed string,
// x-model's input listener has not run -- and since Alpine orders `model` before
// `on`, @input="onTitle()" runs synchronously in the same event dispatch, so
// observing the new title proves onTitle() has already had its chance. Every
// "the slug did not move" assertion in this file is gated on this; without it
// they are assertions about a page that has not reacted yet.
const settleTitle = async (page, expected) => {
  await expect
    .poll(async () => (await readSlugState(page)).alpineTitle, {
      message: `Alpine's title must reach ${JSON.stringify(expected)} before any `
        + 'non-change assertion means anything -- until it does, the input handler has not run'
    })
    .toBe(expected);
};

test('an existing page loads with Alpine live and its hand-written slug marked hand-written', async ({ page }) => {
  await openForm(page, editUrl(readPage.id));

  await expect(page.locator('#page-form')).toHaveCount(1);

  const state = await readSlugState(page);
  expect(state, `page editor state on load: ${JSON.stringify(state)}`).toMatchObject({
    formPresent: true,
    titlePresent: true,
    slugPresent: true,
    alpineInitialised: true,
    // The seed values reached the component. `{{json page.title}}` HTML-escapes
    // its quotes into the attribute; if that ever stopped round-tripping, the
    // x-data expression would throw and alpineInitialised would be false.
    alpineTitle: READ_TITLE,
    alpineSlug: READ_SLUG,
    titleValue: READ_TITLE,
    slugValue: READ_SLUG,
    // THE derivation under test. A slug that differs from slugify(title) is
    // treated as hand-written and must be left alone. Invert the initialiser at
    // alpine-components.js:55 and this is the assertion that fails first --
    // nothing in the DOM distinguishes the two states.
    auto: false
  });
});

test('editing the title of an existing page does not move its slug', async ({ page }) => {
  await openForm(page, editUrl(readPage.id));

  const titleInput = page.locator('#title');
  const slugInput = page.locator('#slug');

  // PRECONDITION, asserted non-vacuously: the component is alive and in the
  // state whose behaviour is being tested. Without this the rest of the test is
  // satisfied by a page with no JavaScript at all.
  const before = await readSlugState(page);
  expect(before, `state before the title edit: ${JSON.stringify(before)}`).toMatchObject({
    formPresent: true,
    alpineInitialised: true,
    auto: false,
    alpineTitle: READ_TITLE,
    alpineSlug: READ_SLUG,
    slugValue: READ_SLUG
  });

  // Real keystrokes at the end of the existing title, not fill(): fill()
  // dispatches a single input event, and the failure mode this whole file
  // guards against is per-keystroke (trap 3 in the header).
  const APPENDED = `${READ_TITLE} and more words`;
  await titleInput.click();
  await titleInput.press('End');
  await titleInput.pressSequentially(' and more words');

  // Settle on a POSITIVE signal before reading the non-change.
  await settleTitle(page, APPENDED);

  const after = await readSlugState(page);
  expect(after, `state after the title edit: ${JSON.stringify(after)}`).toMatchObject({
    alpineInitialised: true,
    // Still hand-written. Deleting `@input="auto = false"` from #slug would not
    // show up here, but inverting the initialiser or letting onTitle() re-arm
    // itself would.
    auto: false,
    alpineTitle: APPENDED,
    titleValue: APPENDED,
    alpineSlug: READ_SLUG,
    slugValue: READ_SLUG
  });

  // ...and it is still unchanged a tick later. The assertions above fire the
  // moment the title lands; a handler that overwrote the slug asynchronously
  // (a $watch, a nextTick, a debounce) would sail past them. This is the only
  // honest way to test "and it stays that way" -- a retrying assertion cannot,
  // because its first poll already passes.
  //
  // MUTATION-PROVEN, not merely argued (M8): give onTitle() an unconditional
  // `setTimeout(() => { this.slug = slugify(this.title) }, 250)`, and the
  // immediate read above PASSES while this one fails, reporting the slug already
  // rewritten to the new title. Delete these four lines and that mutation ships.
  await page.waitForTimeout(300);
  const settled = await readSlugState(page);
  expect(settled, `state 300ms after the title edit: ${JSON.stringify(settled)}`).toMatchObject({
    auto: false,
    alpineSlug: READ_SLUG,
    slugValue: READ_SLUG
  });

  // THE POSITIVE CONTROL, on the same page, the same component instance and the
  // same driving method. Everything above asserts that a value did not change,
  // which is exactly what a dead page produces. This proves the wiring can move
  // the slug and chose not to: clear the slug (re-arming auto-fill) and type one
  // more character, and it fills immediately.
  await slugInput.fill('');
  await titleInput.press('End');
  await titleInput.pressSequentially(' x');
  await settleTitle(page, `${APPENDED} x`);

  const control = await readSlugState(page);
  // Spelled out rather than computed with a local reimplementation of slugify():
  // a test that re-derives the expected string from its own copy of the rule
  // agrees with a broken rule. The prefix is lowercase alphanumerics and single
  // dashes, so this is exactly what alpine-components.js:26-32 produces.
  expect(control, `state after clearing the slug and typing one more character: ${JSON.stringify(control)}`)
    .toMatchObject({
      auto: true,
      alpineSlug: `${READ_TITLE}-and-more-words-x`,
      slugValue: `${READ_TITLE}-and-more-words-x`
    });
  expect(
    control.slugValue,
    'the positive control must actually move the slug, or the non-change above proves nothing'
  ).not.toBe(READ_SLUG);
});

test('clearing the slug re-arms auto-fill and it keeps following every later keystroke', async ({ page }) => {
  await openForm(page, editUrl(readPage.id));

  const titleInput = page.locator('#title');
  const slugInput = page.locator('#slug');

  const start = await readSlugState(page);
  expect(start, `state on load: ${JSON.stringify(start)}`).toMatchObject({
    alpineInitialised: true,
    auto: false,
    alpineSlug: READ_SLUG
  });

  // Emptying the TITLE first, which must not touch the slug: onTitle()'s guard
  // is `this.auto || !this.slug`, and with a hand-written non-empty slug both
  // halves are false. Asserted because it is the closest neighbour to the bug
  // this file is about -- a guard that fired here would blank a live page's URL.
  await titleInput.fill('');
  await settleTitle(page, '');
  const titleCleared = await readSlugState(page);
  expect(titleCleared, `state after clearing the title: ${JSON.stringify(titleCleared)}`).toMatchObject({
    auto: false,
    alpineSlug: READ_SLUG,
    slugValue: READ_SLUG
  });

  // Now clear the SLUG. x-model writes '' into the component and
  // `@input="auto = false"` fires; `auto` is already false, so at this instant
  // NOTHING has re-armed anything -- the emptiness of the slug is the entire
  // signal onTitle() has to work with.
  await slugInput.fill('');
  await expect(slugInput).toHaveValue('');
  const slugCleared = await readSlugState(page);
  expect(slugCleared, `state after clearing the slug: ${JSON.stringify(slugCleared)}`).toMatchObject({
    auto: false,
    alpineSlug: '',
    slugValue: ''
  });

  // Keystroke ONE. This is the refill, and it is the half that survives every
  // mutation: the interesting assertion is `auto: true`.
  await titleInput.click();
  await titleInput.pressSequentially('R');
  await settleTitle(page, 'R');
  const armed = await readSlugState(page);
  expect(armed, `state after the first keystroke: ${JSON.stringify(armed)}`).toMatchObject({
    // Remove `this.auto = true` from onTitle() (alpine-components.js:60) and
    // this line fails on its own, before the final slug ever gets a chance to be
    // wrong. That is why it is asserted separately from the value below.
    auto: true,
    alpineSlug: 'r',
    slugValue: 'r'
  });

  // Keystrokes TWO through FOURTEEN. A single-keystroke test cannot tell a
  // working re-arm from one that fills once and then stops: without
  // `this.auto = true`, keystroke two sees auto === false and slug === 'r'
  // (non-empty), the guard closes, and the slug is frozen at 'r' forever while
  // the title marches on.
  //
  // DEMONSTRATED, not asserted (M5c). The plan's draft wrote this test as
  // `slug.fill(''); title.fill('Re Armed Title'); expect(slug).toHaveValue('re-armed-title')`.
  // Run that shape with `this.auto = true` deleted and it PASSES -- one input
  // event never reaches the second keystroke, so the freeze is invisible and the
  // final value is right by accident. Measured: FINAL SLUG "re-armed-title",
  // green. pressSequentially is what makes this test able to fail.
  await titleInput.pressSequentially('e Armed Title');
  await settleTitle(page, 'Re Armed Title');

  const final = await readSlugState(page);
  expect(final, `state after the full title: ${JSON.stringify(final)}`).toMatchObject({
    auto: true,
    alpineTitle: 'Re Armed Title',
    titleValue: 'Re Armed Title',
    alpineSlug: 're-armed-title',
    slugValue: 're-armed-title'
  });
});

test('submitting after a title edit posts the ORIGINAL slug', async ({ page }) => {
  await openForm(page, editUrl(postPage.id));

  const before = await readSlugState(page);
  expect(before, `state on load: ${JSON.stringify(before)}`).toMatchObject({
    formPresent: true,
    alpineInitialised: true,
    auto: false,
    titleValue: POST_TITLE,
    slugValue: POST_SLUG
  });

  await page.locator('#title').fill(POSTED_TITLE);
  await settleTitle(page, POSTED_TITLE);

  // This is the client-side half of "the URL does not move on save", and the
  // half ar-7v3k check 8 is actually about: whatever the server then does with
  // it, the form must put the UNCHANGED slug on the wire. Asserted on the real
  // request body rather than on the input's value, because the input's value is
  // what the previous test already checked -- a field that reads correctly but
  // is excluded from the serialised body (a lost `name`, a disabled control)
  // would pass there and fail here.
  const [request] = await Promise.all([
    page.waitForRequest((r) => r.method() === 'POST' && new URL(r.url()).pathname === `/pages/${postPage.id}`),
    page.locator('#page-form button[type="submit"]').click()
  ]);

  const posted = new URLSearchParams(request.postData() || '');
  const payload = Object.fromEntries(posted.entries());
  expect(payload, `POSTed form body: ${JSON.stringify(payload)}`).toMatchObject({
    // The POSITIVE half: the submit really carried the edit. Without this, a
    // form that posted nothing but its slug would satisfy the line below.
    title: POSTED_TITLE,
    // ...and the slug the page is served under is untouched. routes/pages.js:123
    // turns an EMPTY slug into null and models/pages.js:130 then regenerates it
    // from the (new) title, so a client-side auto-fill that blanked or rewrote
    // this field is exactly how the public URL would silently move.
    slug: POST_SLUG
  });
});

// DELIBERATELY RED -- see the "PRE-EXISTING PRODUCT DEFECT" block in the header.
// This is the server-side half of the same claim, and it fails on the FIRST
// assertion after the submit: POST /pages/:id answers 404 because
// models/pages.js runs the UPDATE as the anon role and RLS matches no rows.
// Nothing about the slug behaviour is broken; the page simply cannot be saved.
// Thread `res.locals.supabase` into models/pages.js and this test goes green
// with no change to the spec.
test('saving a title edit round-trips the edit and leaves the public URL alone', async ({ page }) => {
  await openForm(page, editUrl(savePage.id));

  const before = await readSlugState(page);
  expect(before, `state on load: ${JSON.stringify(before)}`).toMatchObject({
    formPresent: true,
    alpineInitialised: true,
    auto: false,
    titleValue: SAVE_TITLE,
    slugValue: SAVE_SLUG
  });

  // THE POSITIVE PAYLOAD (trap 2). Submitting an untouched form and finding the
  // slug unchanged proves nothing: a save that silently failed produces exactly
  // that. This edit is something the database can be asked about afterwards, so
  // "the slug did not move" is only reachable through a save that demonstrably
  // happened.
  await page.locator('#title').fill(SAVED_TITLE);
  await settleTitle(page, SAVED_TITLE);

  // Asserted on the RESPONSE, not by waiting for a navigation that will never
  // come: a bare waitForURL here fails as a 30-second timeout with no diagnosis,
  // and this test's whole job is to name what went wrong. Today it reads
  // "expected < 400, received 404".
  const [response] = await Promise.all([
    page.waitForResponse((r) => r.request().method() === 'POST' && new URL(r.url()).pathname === `/pages/${savePage.id}`),
    page.locator('#page-form button[type="submit"]').click()
  ]);
  expect(
    response.status(),
    'POST /pages/:id must succeed; a 404 here is the anon-client RLS defect in models/pages.js, '
      + 'not a slug problem -- see this file\'s header'
  ).toBeLessThan(400);

  // Success, asserted rather than assumed. routes/pages.js:134 redirects to
  // /pages/manage only on success; every failure path goes through sendError,
  // which HX-Retargets an error-inline notification into #alerts and leaves the
  // URL exactly where it was (util/http-error.js:43-46).
  await page.waitForURL((url) => url.pathname === '/pages/manage');
  await expect(page.locator('#alerts .notification.is-danger')).toHaveCount(0);

  // The app's own view of the outcome: the manage table's row for the NEW title
  // still carries the OLD slug. This is the user-visible form of the claim, and
  // it is server-rendered, so it cannot be satisfied by leftover client state.
  const row = page.locator('tbody tr').filter({ has: page.locator(`strong:text-is("${SAVED_TITLE}")`) });
  await expect(row).toHaveCount(1);
  await expect(row.locator('code')).toHaveText(SAVE_SLUG);

  const { rows } = await db.query('select title, slug from pages where id = $1', [savePage.id]);
  expect(rows.length, 'the fixture row must still exist').toBe(1);
  // Read in this order deliberately: if the title assertion fails, the save
  // never round-tripped and the slug assertion below would have been a false
  // green.
  expect(rows[0].title, 'the save must actually have landed, or the slug check below is vacuous').toBe(SAVED_TITLE);
  expect(rows[0].slug, 'the slug -- the public URL -- must not have moved').toBe(SAVE_SLUG);

  // ...and the inbound link still resolves. /pages/:slug is authOptional and
  // this fixture is published + public, so an unauthenticated fetch renders the
  // page itself. The body is checked for the page's own title because a bare
  // 200 is satisfiable by the sign-in page (Task 12's Claim D).
  const publicPage = await page.request.get(`/pages/${SAVE_SLUG}`);
  expect(publicPage.status()).toBe(200);
  const html = await publicPage.text();
  expect(html, 'the old slug must still serve the page, not a sign-in page or a 404')
    .toContain(SAVED_TITLE);
});

test('a new page auto-fills its slug from the title, preserving underscores', async ({ page }) => {
  await openForm(page, '/pages/new');

  // /pages/new renders with `page: null` (routes/pages.js:54), so the x-data
  // expression is `pageSlug(null, null)` -- the `json` helper is
  // `JSON.stringify(v ?? null)` (util/handlebars.js:224), which turns a missing
  // value into the literal `null` rather than an empty string or a syntax error.
  // That is what the `(value || '')` guard in slugify and the `initialTitle || ''`
  // seeds exist for. Asserted against the server's markup, because the live DOM
  // cannot tell "the expression rendered as valid JS" from "Alpine recovered".
  const token = await page.evaluate(() => localStorage.getItem('authToken'));
  expect(token, 'storageState must carry an authToken; this route is authenticated').toBeTruthy();
  const markup = await page.request.get('/pages/new', { headers: { Authorization: `Bearer ${token}` } });
  expect(markup.status()).toBe(200);
  expect(
    await markup.text(),
    'a brand-new page must seed the component with literal nulls, not a broken expression'
  ).toContain('x-data="pageSlug(null, null)"');

  const start = await readSlugState(page);
  expect(start, `state on the new-page form: ${JSON.stringify(start)}`).toMatchObject({
    formPresent: true,
    alpineInitialised: true,
    alpineTitle: '',
    alpineSlug: '',
    titleValue: '',
    slugValue: '',
    // With no slug at all, auto-fill starts ARMED. Invert the initialiser and
    // the slug still fills (the `!this.slug` half of onTitle's guard covers the
    // first keystroke), so this is the only assertion that catches it here.
    auto: true
  });

  await page.locator('#title').click();
  await page.locator('#title').pressSequentially('Foo_Bar Baz Qux');
  await settleTitle(page, 'Foo_Bar Baz Qux');

  const filled = await readSlugState(page);
  // UNDERSCORES SURVIVE, AND THAT IS DELIBERATE. slugify strips `[^\w\s-]`;
  // `_` is a word character and nothing else in the chain targets it, so
  // "Foo_Bar" -> "foo_bar" rather than "foo-bar". This matches the deleted
  // inline script character-for-character (alpine-components.js:12-25). A
  // version that folded underscores into dashes would not merely change new
  // slugs -- it would flip the on-load `initialSlug === slugify(initialTitle)`
  // derivation for every EXISTING page whose title contains one, turning
  // hand-written slugs into auto-following ones. Keep this test.
  expect(filled, `state after typing the title: ${JSON.stringify(filled)}`).toMatchObject({
    auto: true,
    alpineSlug: 'foo_bar-baz-qux',
    slugValue: 'foo_bar-baz-qux'
  });

  // Nothing is submitted here: /pages/new would create a row, and the point of
  // this test is entirely client-side.
});

test('hand-editing the slug stops it following the title', async ({ page }) => {
  // The forward direction of the re-arm test, and the reason `auto` exists at
  // all. Added because it is the ONLY thing that makes `@input="auto = false"`
  // on #slug load-bearing: every other test in this file either starts from an
  // existing page (where auto is already false, so deleting that binding changes
  // nothing) or never touches the slug by hand. Without this test that attribute
  // could be deleted and the whole spec would stay green.
  await openForm(page, '/pages/new');

  const titleInput = page.locator('#title');
  const slugInput = page.locator('#slug');

  const start = await readSlugState(page);
  expect(start, `state on the new-page form: ${JSON.stringify(start)}`).toMatchObject({
    formPresent: true,
    alpineInitialised: true,
    auto: true,
    alpineSlug: ''
  });

  // It follows to begin with -- the positive control for everything below.
  await titleInput.click();
  await titleInput.pressSequentially('Alpha Beta');
  await settleTitle(page, 'Alpha Beta');
  const following = await readSlugState(page);
  expect(following, `state while auto-fill is armed: ${JSON.stringify(following)}`).toMatchObject({
    auto: true,
    alpineSlug: 'alpha-beta',
    slugValue: 'alpha-beta'
  });

  // Now edit the slug by hand. `@input="auto = false"` is the whole of the
  // disarming mechanism; there is no other signal, because a hand-written slug
  // is indistinguishable in the DOM from one auto-fill happened to produce.
  await slugInput.fill('hand-written-slug');
  const disarmed = await readSlugState(page);
  expect(disarmed, `state after hand-editing the slug: ${JSON.stringify(disarmed)}`).toMatchObject({
    auto: false,
    alpineSlug: 'hand-written-slug',
    slugValue: 'hand-written-slug'
  });

  // ...and it stops following, for every later keystroke, not just the next one.
  await titleInput.click();
  await titleInput.press('End');
  await titleInput.pressSequentially(' Gamma Delta');
  await settleTitle(page, 'Alpha Beta Gamma Delta');

  const held = await readSlugState(page);
  expect(held, `state after typing more title: ${JSON.stringify(held)}`).toMatchObject({
    auto: false,
    alpineSlug: 'hand-written-slug',
    slugValue: 'hand-written-slug'
  });
  expect(
    held.slugValue,
    'the slug must not have resumed following the title'
  ).not.toBe('alpha-beta-gamma-delta');
});
